[build]
command = "npm run build && npm run prisma:deploy"
publish = "public"
functions = "dist/netlify/functions"

[[redirects]]
from = "/*"
to = "/.netlify/functions/api/:splat"
status = 200

[functions."sync-open-shipments"]
schedule = "*/15 * * * *"

[functions."process-odoo-queue"]
schedule = "* * * * *"

[functions."run-production-background"]
background = true

[functions."ensure-telegram-webhook"]
schedule = "*/5 * * * *"
