client_id = "eaf022045694e907d4ed6d02bbbfd49a"
name = "viola-telegraph"
handle = "viola-telegraph"
application_url = "https://viola-telegraph-integration.vercel.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

[access_scopes]
scopes = "read_all_orders,read_orders,write_orders,write_order_edits,read_customers,read_products,write_products,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_validations,write_validations"

[auth]
redirect_urls = [ "https://viola-telegraph-integration.vercel.app/api/auth" ]
