uid = "1cc55f71-32b5-9ade-2c50-81c9fe3774bd4e0e02db"
[[extensions]]
name = "t:name"
handle = "make-telegraph-shipment"
type = "admin_link"

[[extensions.targeting]]
target = "admin.order-details.action.link"
url = "/orders/make-telegraph?adminToken=9ee18931cdbb2b4d9549795e28f4183e"

[[extensions]]
name = "Make Odoo Sales Order"
handle = "make-odoo-sales-order"
type = "admin_link"

[[extensions.targeting]]
target = "admin.order-details.action.link"
url = "/orders/create-odoo-sales-order?adminToken=9ee18931cdbb2b4d9549795e28f4183e"

[[extensions]]
name = "Make Telegraph shipments"
handle = "make-telegraph-shipments-bulk"
type = "admin_link"

[[extensions.targeting]]
target = "admin.order-index.selection-action.link"
url = "/orders/make-telegraph/bulk?adminToken=9ee18931cdbb2b4d9549795e28f4183e"

[[extensions]]
name = "Make Odoo Sales Orders"
handle = "make-odoo-sales-orders-bulk"
type = "admin_link"

[[extensions.targeting]]
target = "admin.order-index.selection-action.link"
url = "/orders/create-odoo-sales-order/bulk?adminToken=9ee18931cdbb2b4d9549795e28f4183e"
