api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "require-telegraph-location"
type = "function"
uid = "b5707a05-54c8-e867-be0c-40c4d8da330602d3b4eb"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
