import { QueueClient } from '@vercel/queue';

// These files are generated by the project build before Vercel bundles the API
// entrypoints, matching api/index.ts's single-source build arrangement.
// @ts-expect-error dist output exists after `npm run build`.
import { parseProductionResumePayload } from '../dist/services/productionContinuation.js';
// @ts-expect-error dist output exists after `npm run build`.
import { resumeProductionInvocation } from '../dist/netlify/functions/run-production-background.js';

class InvalidProductionQueuePayloadError extends Error {}

const queue = new QueueClient();

export default queue.handleNodeCallback(
  async (message: unknown, metadata) => {
    const payload = parseProductionResumePayload(message);
    if (!payload) {
      console.error('[production-queue] Invalid payload', {
        messageId: metadata.messageId,
        receivedType: Array.isArray(message) ? 'array' : typeof message,
      });
      throw new InvalidProductionQueuePayloadError('Invalid production queue payload');
    }
    try {
      await resumeProductionInvocation(payload.chatId, payload.batchId);
    } catch (error) {
      console.error('[production-queue] Invocation failed', {
        messageId: metadata.messageId,
        batchId: payload.batchId,
        error: error instanceof Error ? `${error.name}: ${error.message}` : String(error),
      });
      throw error;
    }
  },
  {
    visibilityTimeoutSeconds: 300,
    retry: (error, metadata) => {
      if (error instanceof InvalidProductionQueuePayloadError) return { acknowledge: true };
      console.warn('[production-queue] Scheduling retry', {
        messageId: metadata.messageId,
        deliveryCount: metadata.deliveryCount,
        error: error instanceof Error ? `${error.name}: ${error.message}` : String(error),
      });
      return { afterSeconds: Math.min(300, 10 * (2 ** Math.min(metadata.deliveryCount - 1, 5))) };
    },
  }
);
